### DISCUSSION TITLE
Are the `model_checker` config options all `snake_case`?

### DISCUSSION THREAD

**Discussion by PaulRBerg** [foundry-rs/foundry#4297] [Help] [answered]
It is not clear from the example config shown in the README whether the SMT model checker configuration options are all `snake_case`, or they follow the standard `camelCase` of the Solidity standard JSON?

This is what it is currently shown in the README:

```toml
[profile.default.model_checker]
contracts = { 'src/Contract.sol' = [ 'Contract' ] }
engine = 'chc'
timeout = 10000
targets = [ 'assert' ]
```

But there are other config options that are made up of multiple words, e.g. `showUnproved`. Should this be written like this:

```toml
[profile.default.model_checker]
showUnproved = true
```

Or like this?

```toml
[profile.default.model_checker]
show_unproved = true
```

I can't quite tell which way works because I am still grappling with the SMTChecker.
