### DISCUSSION TITLE
Confusion with scripting and rpc aliases

### DISCUSSION THREAD

**Discussion by oveddan** [foundry-rs/foundry#4742] [General]
In the [scripting docs](https://book.getfoundry.sh/tutorials/solidity-scripting?highlight=scri#solidity-scripting), it instructs on how to specify rpc  config based on aliases:

```toml
[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
```

However, it never specifies how to run a script using these aliases; the only way it shows is how to manually specify the rpc url:
`forge script script/NFT.s.sol:MyScript --rpc-url $GOERLI_RPC_URL --broadcast --verify -vvvv`

Is there a way to run the script and just have the rpc url and etherscan api key be loaded via the chain alias without specifying the rpc url in the script command?
