### DISCUSSION TITLE
How to install Foundry in a GitPod config?

### DISCUSSION THREAD

**Discussion by PaulRBerg** [foundry-rs/foundry#6689] [General]
I've tried to use the following config, but it didn't work:

```yaml
image: "gitpod/workspace-node:latest"

tasks:
  - name: "Install dependencies"
    before: "curl -L https://foundry.paradigm.xyz | bash"
    init: "npm install"

vscode:
  extensions:
    - "esbenp.prettier-vscode"
    - "NomicFoundation.hardhat-solidity"
```

Running `forge` did not work:

> bash: forge: command not found
