### DISCUSSION TITLE
Question concerning anvil, docker and websockets

### DISCUSSION THREAD

**Discussion by arondius** [foundry-rs/foundry#7172] [Help]
Hi guys :)

Hope you can help met out.

Question concerning anvil, docker and websockets:

I have a docker compose project:
```
version: '3.8'

services:

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    env_file:
      - .env
    environment:
      - ANVIL_FORK_URL=${ANVIL_FORK_URL}
    ports:
      - 8545:8545
    container_name: anvil
    entrypoint: anvil -f $ANVIL_FORK_URL --host 0.0.0.0

  src:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: src_container
```
The src container is a Typescript node app with EthersJs to set up a websocket provider. When running agains mainnet the app can succesfully subscribe to websocket events.

When using the Anvil local fork, it can connect to anvil through the ```ws://anvil:8545 docker container```, I can see the connection in the anvil container logs.
However there is no subscription data coming in to my app

Going into the src container and doing a
```wscat -c ws://anvil:8545
> {"id":1,"jsonrpc":"2.0","method":"eth_subscribe","params":["newHeads"]}
< {"jsonrpc":"2.0","id":1,"result":"0x5536365230446d756177526b31727479"}
```
The above results in only one piece of data, not a stream of data

What am i missing?
