### ISSUE TITLE
feat(`forge fmt`): handle multiple lines of comments

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#10173]
### Component

Forge

## Problem

Suppose you have some comments like this:

```solidity
/// @notice Calculates the amount that the sender would be refunded if the stream were canceled, denoted in units
/// of the token's decimals.
```

I'm using a `line_length` of 120, so if I change `denoted `to `denominated`, like so:

```solidity
/// @notice Calculates the amount that the sender would be refunded if the stream were canceled, denominated in units
/// of the token's decimals.
```

And then I run `forge fmt`, the following output will be produced:

```solidity
/// @notice Calculates the amount that the sender would be refunded if the stream were canceled, denominated in
/// units
/// of the token's decimals.
```

As you can see, `units` has been pushed on line 2, and the rest of the comments have been pushed on line 3.

## Solution

Make `forge fmt` handle multiple lines of comments, and produce this output instead:

```solidity
/// @notice Calculates the amount that the sender would be refunded if the stream were canceled, denominated in
/// units of the token's decimals.
```

cc @rkrasiuk IIRC you were working on `forge fmt`!

## Screen Recording

https://github.com/user-attachments/assets/52001d4a-4425-4690-b241-48e123ae43a6

### Additional context

This my `[fmt`] configuration in `foundry.toml`:

```toml
[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
```
