### ISSUE TITLE
Can't verify an etherscan contract on the hoodi testnet without explicitly specifying `chain` and `url` in `[etherscan]`

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [foundry-rs/foundry#10194]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

5699fab4c8917d7d0f542fc552dc88afe543ccc7

### What version of Foundryup are you on?

1.0.1

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

probably [hoodi testnet](https://github.com/eth-clients/hoodi) has not been added as known chain yet

```toml
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }
# doesn't work
hoodi = { key = "${ETHERSCAN_API_KEY}" }
# works
hoodi = { key = "${ETHERSCAN_API_KEY}", chain = 560048, url = "https://api-hoodi.etherscan.io/api" }
```

```bash
source .env
forge script script/Counter.s.sol:CounterScript --rpc-url $HOODI_RPC_URL --broadcast --verify -vvvv
```

```
Attempting to verify on Sourcify. Pass the --etherscan-api-key <API_KEY> to verify on Etherscan, or use the --verifier flag to verify on another provider.
```
