### ISSUE TITLE
Make the crate generated by `forge bind` depend on `alloy` through crates.io instead of git

### ISSUE THREAD

**Issue by guidanoli** [foundry-rs/foundry#10197]
### Component

Forge

### Describe the feature you would like

Currently, when you run `forge bind`, it generates a crate (under `out/bindings` by default).
Below is the generated `Cargo.toml` file:

```toml
[package]
name = "foundry-contracts"
version = "0.1.0"
edition = "2021"

[dependencies] 
alloy = { git = "https://github.com/alloy-rs/alloy", features = ["sol-types", "contract"] }
```

This creates has some problem for projects that try to publish it to [crates.io](https://crates.io/):

- It doesn't contain a license and description, which are required by crates.io. This is being tracked by #6844.
- It depends on `alloy` through git, and not crates.io.

This issue is about the second item.
One solution is to edit this `Cargo.toml` with `tomlq`, but ideally we would like `forge` to generate the crate in a format that can already be published to crates.io without any extra intervention.

Below is the desired diff:

```diff
7c7
< alloy = { git = "https://github.com/alloy-rs/alloy", features = ["sol-types", "contract"] }
---
> alloy = { version = "0.12.4", features = ["sol-types", "contract"] }
```

Do note that we specified the version of alloy.
If not specified, Forge could specify one by default.
