### ISSUE TITLE
feat(foundry-cli::utils): add new allocators + tracing features

### ISSUE THREAD

**Issue by mablr** [foundry-rs/foundry#10530]
### Component

Other (please describe)

### Describe the feature you would like

Following #10523 (abstract global allocator in `foundry-cli`), we could extend the allocator module to support multiple allocators and tracing.

### Proposed Changes
1. Add support for multiple allocators:
   - `jemalloc` (current)
   - `mimalloc`
   - `snmalloc`

2. New feature flags:
```toml
[features]
default = ["jemalloc"]
jemalloc = ["foundry-cli/jemalloc"]
mimalloc = ["foundry-cli/mimalloc"]
snmalloc = ["foundry-cli/snmalloc"]
tracy-allocator = ["foundry-cli/tracy-allocator"]
```

### Questions
1. Which allocators to implement?
2. Should we include `tracy-allocator` feature?

I would like to be assigned to implement this feature if the team considers it valuable.

### References
- [Solar's allocator configuration](https://github.com/paradigmxyz/solar/blob/86b5bd276e72be4745cfb5cbcd5c7e029152b36e/crates/cli/src/utils.rs#L5-L44)
- [Reth's allocator configuration](https://github.com/paradigmxyz/reth/blob/e6ce41ebba0d8752cef9ed885aae057e09226d05/crates/cli/util/src/allocator.rs)
