### ISSUE TITLE
feat(`config`): improve documentation around usage of `--chain` and `--rpc-url`

### ISSUE THREAD

**Issue by mshakeg** [foundry-rs/foundry#10631]
### Component

Forge

## Summary

Extend Foundry's chain configuration system to include chain IDs alongside RPC URLs in `foundry.toml`, enabling the `--chain` flag to work seamlessly with custom chains and improving integration with StdChains.

## Problem Statement

Currently, Foundry's chain configuration has several limitations that create friction in the developer experience:

### 1. Limited `--chain` Flag Functionality

The `--chain` flag only works with pre-defined chains in `StdChains` (`mainnet`, `polygon`, etc.). For custom or newer chains not included in the default set, developers must:
- Use `--rpc-url` instead of the more intuitive `--chain` to use the rpc url for a specified chain alias.

### 2. StdChains Integration Gap

When working with custom chains in Solidity scripts, developers must manually add chain data:
```solidity
// Current workaround required
setChain("unichain", ChainData("Unichain", 130, ""));
Chain memory chain = getChain("unichain");
```

This breaks the seamless experience that `StdChains` provides for default chains.

### 3. Inconsistent Configuration Experience

Developers configure RPC URLs in `foundry.toml`:
```toml
[rpc_endpoints]
unichain = "${UNICHAIN_MAINNET_RPC_URL}"
```

But this configuration doesn't enable full chain functionality - it only works for RPC calls, not for script execution or `StdChains` integration.

### Enhanced `foundry.toml` Configuration

Extend the configuration format to include chain IDs alongside RPC URLs:

```toml
[rpc_endpoints]
mainnet = { url = "${MAINNET_RPC_URL}", chain_id = 1 }
unichain = { url = "${UNICHAIN_MAINNET_RPC_URL}", chain_id = 130 }
polygon = { url = "${POLYGON_RPC_URL}", chain_id = 137 }
# ...
```

### Backward Compatibility

Maintain full backward compatibility with existing configurations:
```toml
[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"  # Still works as before
unichain = { url = "${UNICHAIN_MAINNET_RPC_URL}", chain_id = 1301 }  # New format
```

### 1. Seamless `--chain` Flag Usage
```bash
# This would work for any configured chain
forge script script/Deploy.s.sol --chain unichain --account deployer --broadcast
```

### 2. Automatic StdChains Integration
```solidity
// Would work automatically without manual setup
Chain memory chain = getChain(1301);  // By chain ID
Chain memory chain = getChain("unichain");  // By alias
```

### 3. Built-in Validation
Foundry could perform sanity checks:
- Verify the actual chain ID matches the configured chain ID when connecting
- Warn about mismatches between configured and actual chain IDs
- Provide helpful error messages for chain configuration issues

### 4. Unified Configuration Experience
One configuration enables:
- Script execution with `--chain`
- RPC calls with aliases
- StdChains integration
- Verification with proper chain context

### 1. Chain ID Discovery
For configurations without explicit chain IDs, Foundry could:
- Auto-discover chain ID on first connection
- Cache the result for future use
- Provide warnings about missing chain ID configuration

### 2. Configuration Validation
- Validate that URLs are reachable and return expected chain IDs
- Provide clear error messages for configuration mismatches
- Support dry-run validation commands

### 3. Migration Path
- Provide tooling to help migrate existing configurations
- Auto-generate chain ID mappings for common networks
- Clear documentation on migration benefits

### 1. Multi-Chain Development
```bash
# Deploy to multiple chains with consistent commands
forge script script/Deploy.s.sol --chain mainnet --broadcast
forge script script/Deploy.s.sol --chain unichain --broadcast  
forge script script/Deploy.s.sol --chain polygon --broadcast
```

### 2. Chain-Aware Scripts
```solidity
function run() external {
    Chain memory currentChain = getChain(block.chainid);
    console.log("Deploying to:", currentChain.name);
    
    // Chain-specific logic without manual configuration
    if (currentChain.chainId == 1301) {
        // Unichain-specific deployment logic
    }
}
```

## Related Issues

This enhancement would address several common developer pain points:
- Confusion about when to use `--chain` vs `--rpc-url`
- Manual `StdChains` configuration for custom networks
- Inconsistent chain configuration across different Foundry commands
