### ISSUE TITLE
`vm.getChain(block.chainid).chainAlias` returns chain id

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [foundry-rs/foundry#10801]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

1.2.3-stable

### What version of Foundryup are you on?

1.0.1

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

instead of chainAlias I got chain id (17000)

```solidity
    /// Information about a blockchain.
    struct Chain {
        // The chain name.
        string name;
        // The chain's Chain ID.
        uint256 chainId;

        // The chain's alias. (i.e. what gets specified in `foundry.toml`).
        string chainAlias;
        // ^^^

        // A default RPC endpoint for this chain.
        string rpcUrl;
    }
```

```bash
forge init counter
cd counter
```

`./foundry.toml`
```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
optimizer = true
extra_output_files = ["irOptimized"]
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
revert_strings = "strip"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
hoodi = "${HOODI_RPC_URL}"
```

`./script/Counter.s.sol`
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {Counter} from "../src/Counter.sol";

contract CounterScript is Script {
    Counter public counter;

    function setUp() public {}

    function run() public {
        vm.startBroadcast();

        console.log(vm.getChain(block.chainid).name);
        console.log(vm.getChain(block.chainid).chainAlias);

        vm.stopBroadcast();
    }
}
```

```bash
export HOLESKY_RPC_URL="https://ethereum-holesky-rpc.publicnode.com"
forge script script/Counter.s.sol:CounterScript --rpc-url $HOLESKY_RPC_URL --broadcast -vvvv
```

```
== Logs ==
  holesky
  17000 //chainAlias
```
