### ISSUE TITLE
feat(anvil): add --host option

### ISSUE THREAD

**Issue by alephao** [foundry-rs/foundry#1570]
### Component

Anvil

### Describe the feature you would like

When trying to run anvil on a docker container, the endpoint is not exposed outside of the container because it's binded to `127.0.0.1`, but docker requires `0.0.0.0`

Example docker-compose file:

```yml
version: "3"
services:
  chain:
    image: ghcr.io/foundry-rs/foundry:nightly-85f69d950505e92d2047f38c3ca69281fc0e000b
    ports: 
      - "8545:8545"
    entrypoint: anvil --accounts 20
```

Would be great to have a `--host` param or something similar so I could choose `--host 0.0.0.0` and be able to use anvil via docker.

**Comment by Rogalek** [comment]
is this working for you? how to use that?
I am trying to do this:
```
services:
  redis:
    image: redis:latest
  foundry:
    container_name: foundry
    env_file: .env
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil -f $RPC_URL --no-rate-limit --gas-limit 30000000 --fork-block-number 106402958 --host 0.0.0.0
    ports:
      - "8545:8545"
  tests:
    env_file: .env
    build:
      dockerfile: "./Dockerfile.test"
      context: .
      args:
        - CONFIG=$CONFIG
    command: pytest . -c $CONFIG
    volumes:
      - .:/code
    depends_on:
      - redis
      - foundry

```

but still when I run docker-compose up I will get this message:
```
(repo-py3.11) rogal@rogal-Legion:~/Documents/repo/repo$ docker-compose -f docker-compose-test.yaml up
Starting foundry           ... done
Starting repo_redis_1 ... done
Starting repo_tests_1 ... done
Attaching to foundry, repo_redis_1, repo_tests_1
redis_1        | 1:C 05 Aug 2023 08:43:36.928 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1        | 1:C 05 Aug 2023 08:43:36.928 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1        | 1:C 05 Aug 2023 08:43:36.928 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1        | 1:M 05 Aug 2023 08:43:36.929 * monotonic clock: POSIX clock_gettime
redis_1        | 1:M 05 Aug 2023 08:43:36.931 * Running mode=standalone, port=6379.
redis_1        | 1:M 05 Aug 2023 08:43:36.931 # Server initialized
foundry        | 
foundry        | 
foundry        |                              _   _
foundry        |                             (_) | |
foundry        |       __ _   _ __   __   __  _  | |
foundry        |      / _` | | '_ \  \ \ / / | | | |
foundry        |     | (_| | | | | |  \ V /  | | | |
foundry        |      \__,_| |_| |_|   \_/   |_| |_|
foundry        | 
foundry        |     0.1.0 (114e69d 2023-07-25T11:50:55.419172631Z)
foundry        |     https://github.com/foundry-rs/foundry
foundry        | 
foundry        | Available Accounts
foundry        | ==================
foundry        | 
foundry        | (0) "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" (10000.000000000000000000 ETH)
foundry        | (1) "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" (10000.000000000000000000 ETH)
foundry        | (2) "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC" (10000.000000000000000000 ETH)
foundry        | (3) "0x90F79bf6EB2c4f870365E785982E1f101E93b906" (10000.000000000000000000 ETH)
foundry        | (4) "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65" (10000.000000000000000000 ETH)
foundry        | (5) "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc" (10000.000000000000000000 ETH)
foundry        | (6) "0x976EA74026E726554dB657fA54763abd0C3a0aa9" (10000.000000000000000000 ETH)
foundry        | (7) "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955" (10000.000000000000000000 ETH)
foundry        | (8) "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f" (10000.000000000000000000 ETH)
foundry        | (9) "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720" (10000.000000000000000000 ETH)
foundry        | 
foundry        | Private Keys
foundry        | ==================
foundry        | 
foundry        | (0) 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
foundry        | (1) 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
foundry        | (2) 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
foundry        | (3) 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
foundry        | (4) 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
foundry        | (5) 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
foundry        | (6) 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e
foundry        | (7) 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
foundry        | (8) 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
foundry        | (9) 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
foundry        | 
foundry        | Wallet
foundry        | ==================
foundry        | Mnemonic:          test test test test test test test test test test test junk
foundry        | Derivation path:   m/44'/60'/0'/0/
foundry        | 

foundry        | Chain ID
foundry        | ==================
foundry        | 
foundry        | 31337
foundry        | 
foundry        | Base Fee
foundry        | ==================
foundry        | 
foundry        | 1000000000
foundry        | 
foundry        | Gas Limit
foundry        | ==================
foundry        | 
foundry        | 30000000
foundry        | 
foundry        | Genesis Timestamp
foundry        | ==================
foundry        | 
foundry        | 1691225016
foundry        | 
foundry        | Listening on 127.0.0.1:8545

```

what am I doing wrong?
