### ISSUE TITLE
`FOUNDRY_PROFILE` doesn't inherit default

### ISSUE THREAD

**Issue by wiasliaw** [foundry-rs/foundry#1628]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (35f60f1 2022-05-15T15:48:25.005787Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

According to [config reference docs](https://book.getfoundry.sh/reference/config.html#profiles), other profile should inherit the default profile.

Error reproduce below.
```toml
# foundry.toml
[default]
src = 'src'
out = 'dist'
libs = ['lib']

[test]
# config nothing
```

Then run command:
```sh
export FOUNDRY_PROFILE="test"
forge build
```

The compiled files will place in `out` folder, not `dist`.
