### ISSUE TITLE
Model checker paths have to be absolute

### ISSUE THREAD

**Issue by SamWilsn** [foundry-rs/foundry#1683]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry

### What version of Foundry are you on?

forge 0.2.0 (0e6c8fb 2022-05-21T03:23:31.545158869Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

The model checker plugin paths should be relative to `foundry.toml`. For example, this should work:

```toml
[default.model_checker]
contracts = { 'src/Contract.sol' = [ 'Contract' ] }
engine = 'chc'
timeout = 10000
targets = [ 'assert' ]
```
