### ISSUE TITLE
Bug: `forge config` won't recognize `node_modules` in presence of `lib` 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#1721]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge config

### Operating System

macOS (Intel)

### Describe the bug

running `forge config` in a repo with both a `node_modules` and `lib` directory will not generate remappings for the node_modules directory

**Comment by sambacha** [comment]
> couldn't reproduce this is this still an issue?

I just confirmed it.

To reproduce:

### 1. Clean clone and install 
```bash
git clone https://github.com/gakonst/v3-periphery-foundry v3-test/
cd v3-test
yarn install --mutex file
sleep 1
forge config > foundry.toml
```
outputs:
```toml
[default]
allow_paths = []
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
broadcast = 'broadcast'
bytecode_hash = 'ipfs'
cache = true
cache_path = 'cache'
evm_version = 'london'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_reports = ['*']
ignored_error_codes = [
    1878,
    5574,
]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['node_modules']
memory_limit = 33554432
names = false
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 200
out = 'out'
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solidity-parser/=node_modules/solhint/node_modules/@solidity-parser/',
    '@uniswap/=node_modules/@uniswap/',
    'base64-sol/=node_modules/base64-sol/',
    'contracts/=node_modules/@uniswap/lib/contracts/',
    'hardhat/=node_modules/hardhat/',
]
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = false
sparse_mode = false
src = 'contracts'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 0
via_ir = false

[default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'
```

### 2. Then
```bash
forge install dapphub/ds-test --no-commit
forge config
````
#### Produces 
> truncated toml file for brevity 
```toml
[default]
libs = [
    'node_modules',
    'lib',
]
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solidity-parser/=node_modules/solhint/node_modules/@solidity-parser/',
    '@uniswap/=node_modules/@uniswap/',
    'base64-sol/=node_modules/base64-sol/',
    'contracts/=node_modules/@uniswap/lib/contracts/',
    'ds-test/=lib/ds-test/src/',
    'hardhat/=node_modules/hardhat/',
]
```

### 3. Bug

```bash
mv foundry.toml f.toml
forge config
```
#### Produces config with missing remappings 
```toml
[default]
allow_paths = []
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
broadcast = 'broadcast'
bytecode_hash = 'ipfs'
cache = true
cache_path = 'cache'
evm_version = 'london'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_reports = ['*']
ignored_error_codes = [
    1878,
    5574,
]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['lib']
memory_limit = 33554432
names = false
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 200
out = 'out'
remappings = ['ds-test/=lib/ds-test/src/']
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = false
sparse_mode = false
src = 'contracts'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 0
via_ir = false

[default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'
```
