### ISSUE TITLE
Add RPC endpoint table

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1935]
### Component

Forge

### Describe the feature you would like

With additional fork cheatcodes (#1715) using multiple endpoints will be possible, therefore we need a way to provide an easy way to configure them so they can be used as alias, like

`vm.createFork("optimism")`

This should be an additional toml table that also supports env vars:

```toml
[default.rpc-endpoints]
optimism = "$OP_RPC"
mainnet = "HTTP://......"
```
