### ISSUE TITLE
Foundry panic when running forge test from a Github action

### ISSUE THREAD

**Issue by daedlock** [foundry-rs/foundry#2376]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (114413c 2022-07-19T00:08:18.125698929Z)

### What command(s) is the bug in?

forge test --fork-url $URL

### Operating System

Linux

### Describe the bug

When running from a github action via ` onbjerg/foundry-toolchain@v1` . Foundry panics with the following error

```
The application panicked (crashed).
Message:  Failed to get account for 0xb4c7…7e84
ProviderError(SerdeJson { err: Error("EOF while parsing a value", line: 1, column: 0), text: "" })
Location: evm/src/executor/fork/backend.rs:263
```

The github action file for reference is:

```
on: [push]

name: Unit Tests

jobs:
  check:
    name: Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: cli info
        run: |
          forge --version
      - name: Run tests
        run: make test
```

## Makefile
```
-include .env.ci
.PHONY: all test clean

# deps
install:; forge install
update:; forge update

# Build & test
build:; forge build
test:; forge test --fork-url $FILTERED_OUT_URL
trace:; forge test -vvv
clean:; forge clean
snapshot:; forge snapshot
fmt:; forge fmt
```
