### ISSUE TITLE
Feature: support distributed tracing for Anvil

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2402]
### Component

Anvil

## Feature: Distributed Tracing for Anvil

In order to make a system observable, it must be instrumented. That is, the code must emit [traces](https://opentelemetry.io/docs/concepts/observability-primer/#distributed-traces), [metrics](https://opentelemetry.io/docs/concepts/observability-primer/#reliability--metrics), and [logs](https://opentelemetry.io/docs/concepts/observability-primer/#logs). The instrumented data must then be sent to an Observability back-end. There are a number of Observability back-ends out there, ranging from self-hosted open-source tools (e.g. [Jaeger](https://www.jaegertracing.io/) and [Zipkin](https://zipkin.io/)), to commercial SAAS offerings. This feature request asks for Open Telemetry to be integrated into Anvil. 

For reference, Hyperledger Besu has support for OTEL. 

## Example: OTEL Config w/ docker-compose

```yaml
# otel-collector-config.yml:
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]
```

```yaml
# docker-compose.yml
version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.11.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55680:55680" # zpages extension
    depends_on:
      - zipkin
  foundry:
    image: manifoldfinance/foundry
    container_name: foundry
    command:
      - '--config.file=/etc/foundry/foundry.toml'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - overlay
    deploy:
      endpoint_mode: vip
    volumes:
      - ./foundry:/etc/foundry
      - forge_data:/foundry
    environment:
      ETH_RPC_URL: development
      DAPP_SOLC_VERSION: 0.8.15
      DAPP_TEST_VERBOSITY: 1
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app:cached
    - .:/opt/solc:cached

  #Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
      - ```

### Additional context


part of https://github.com/foundry-rs/foundry/issues/2396
