### ISSUE TITLE
Bug: Forge unable to fix config when root is [default], others have [profile.*]

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2511]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4b720c2 2022-07-28T00:04:25.986568Z)

### What command(s) is the bug in?

forge config --fix

### Operating System

macOS (Intel)

### Describe the bug

```console
Unknown section [default] found in foundry.toml.
```

Trying to run `forge config --fix` on the following .toml file gives:
```console
warning: Could not fix [default] in TOML at foundry.toml: [profile.default] already exists
```

```toml
[default]
allow_paths = ['interfaces', 'contracts']
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
broadcast = 'broadcast'
bytecode_hash = 'none'
cache = true
cache_path = 'cache'
evm_version = 'london'
# includes the contract's metadata in the contract's json artifact
extra_output = []
# emits the output selection as separate json artifact files
extra_output_files = ['metadata']

ffi = false
force = false
fuzz_max_global_rejects = 65_536
fuzz_max_local_rejects = 16_384
# The number of test cases that must execute for each property test
fuzz_runs = 512
# This is an Option, so we can determine in fork mode whether to use the config's gas price
# (if set by user) or the remote client's gas price Option<u64>
gas_price = 10
gas_limit = 9223372036854775807
gas_reports = ['*']
# ignored_error_codes
# 2018 Function state mutability can be restricted to pure
# 3420 Source file does not specify required compiler version!
ignored_error_codes = [
	1878,
	2018,
	3420,
]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = [
	'lib',
	'node_modules',
]
memory_limit = 33554432
names = false
no_storage_caching = false
offline = false
# revert_strings = "verboseDebug"
out = 'out'
remappings = [
	'@openzeppelin/=node_modules/@openzeppelin/',
	'@uniswap/=node_modules/@uniswap/',
	'ds-test/=lib/forge-std/lib/ds-test/src/',
	'forge-std/=lib/forge-std/src/',
]
script = 'script'
sender = '0xafFEaFFEAFfeAfFEAffeaFfEAfFEaffeafFeAFfE'
sizes = false
sparse_mode = false
src = 'contracts'
test = 'test'
tx_origin = '0xAaaaAaAAaaaAAaAAaAaaaaAAAAAaAaaaAaAaaAA0'
verbosity = 2
via_ir = true
revert_strings = "debug"
optimizer = true
optimizer_runs = 1_337
optimizerSteps = ''

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[profile.ci]
optimizer = true
fuzz_runs = 4069
force = true
verbosity = 4

# [default.model_checker]
# contracts = { '/path/to/project/src/Contract.sol' = [ 'Contract' ] }
# engine = 'chc'
# timeout = 10000
# targets = [ 'assert' ]

# [default.optimizer_details]
# constantOptimizer = true
# yul = true
# this sets the `yulDetails` of the `optimizer_details` for the `default` profile
# [default.optimizer_details.yulDetails]
# stackAllocation = true
# optimizerSteps = 'gTVnfClhnfncITgcraonvcgMtjmCumgUmdgdxVeiOlvdOvarhngxiUaxVhOdjTTDODDdUMrTthUVrrnhrjsvcjVuDmletlOThul'
```
