### ISSUE TITLE
Resolving Env which is set by `vm.setEnv`

### ISSUE THREAD

**Issue by wiasliaw** [foundry-rs/foundry#2514]
### Component

Forge

### Describe the feature you would like

In [config reference](https://book.getfoundry.sh/reference/config#rpc_endpoints), `rpc_endpoints` is enable to take environment variable, like `mainnet = "${RPC_MAINNET}"`.

However, it only available when env is exist or provide in command, i.e. `RPC_MAINNET=https://... forge ....`. It cannot take env which is set by cheatcode `setEnv`.

Use case is that: Read Alchemy API key through `vm.setEnv` and resolve in config for multiple fork.

```toml
[rpc_endpoints]
optimism = "https://optimism.alchemyapi.io/v2/${ALCHEMY_KEY}"
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_KEY}"
```
