### ISSUE TITLE
Bad fork_url provider: RelativeUrlWithoutBase

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#2860]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (29ff0b0 2022-08-20T00:05:53.843766Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm not able to read the rpc url correctly from the .env file.

I currently have a .env file with the following rpc
```.env
RPC_MUMBAI=https://rpc.ankr.com/polygon_mumbai
```

Foundry.toml
```toml
[profile.default]
eth_rpc_url = "${RPC_MUMBAI}"
```

Running `forge script` gives the following error.

```sh
The application panicked (crashed).
Message:  Bad fork_url provider: RelativeUrlWithoutBase
Location: /Users/runner/work/foundry/foundry/utils/src/lib.rs:801
```

As a sanity check, changing my .toml to
```toml
[profile.default]
# eth_rpc_url = "${RPC_MUMBAI}"

[rpc_endpoints]
mumbai = "${RPC_MUMBAI}"
```
and logging `vm.rpcUrl('mumbai')` returns the correct rpc url.
Also, running `forge script` with `vm.selectFork(vm.createFork("mumbai"));` at the start runs on the correct fork.
