### ISSUE TITLE
Add `ignore` key to `[fmt]` section

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#3308]
### Component

Forge

### Describe the feature you would like

An array of excluded blobs would be very useful, e.g.:

```toml
[fmt]
ignore = ['**/vendor/*','**/preprocessed/*']
```
