### ISSUE TITLE
[rpc_endpoints] alias not working

### ISSUE THREAD

**Issue by JonasMS** [foundry-rs/foundry#3433]
### Component

Cast

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (82a74a6 2022-10-01T00:07:32.126813Z)

### What command(s) is the bug in?

cast storage

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `cast storage [contract_address] 0 --rpc-url mainnet` results in
```
Error:
Invalid provider url: mainnet

Context:
- Error #0: builder error: relative URL without a base
- Error #1: relative URL without a base
```

`foundry.toml`:
```toml
[default.rpc_endpoints]
mainnet = 'https://mainnet.infura.io/v3/[my_api_key]'
```

Running `... --rpc-url https://mainnet.infura.io/v3/[my_api_key]` works as expected.
