### ISSUE TITLE
cast command doesn't resolve config `[etherscan]`

### ISSUE THREAD

**Issue by wiasliaw** [foundry-rs/foundry#3824]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (250cc85 2022-12-02T19:51:40.34571Z)

### What command(s) is the bug in?

cast etherscan-source --chain mainnet  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2

### Operating System

macOS (Apple Silicon)

### Describe the bug

I don't know if I miss something to config or what else.

## global config

`$HOME/.foundry.toml`

```toml
[rpc_endpoints]
mainnet  = "xxxx"

[etherscan]
mainnet = { key = "xxxx", chain = "mainnet" }
```

## run command with global config

```sh
cast etherscan-source --chain mainnet -d weth  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2

Error:
No Etherscan API Key is set. Consider using the ETHERSCAN_API_KEY env var, or setting the -e CLI argument or etherscan-api-key in foundry.toml
```
