### ISSUE TITLE
bug(fmt): `bracket_spacing` not respected for named args and structs

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4020]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44159a 2023-01-03T00:04:41.810446Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge fmt` does not respect the `bracket_spacing` rule for named function args:

```solidity
function a(uint256 foo) public pure {
    foo;
}

function b() public pure {
    a( {foo: 5} );
}
```

The above gets formatted to:

```solidity
a({foo: 5});
```

Even if `bracket_spacing` is set to `true` in the Foundry config.

#### Update

It looks like this doesn't work for structs either. This:

```solidity
amounts: Amounts({ deposit: args.amounts.netDeposit, withdrawn: 0 }),
```

Gets re-formatted to:

```solidity
amounts: Amounts({deposit: args.amounts.netDeposit, withdrawn: 0}),
```

I have updated the title of the issue to mention both named args and structs.

### Additional context

This is my `[fmt]` configuration:

```toml
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
variable_override_spacing = false
wrap_comments = true
```
