### ISSUE TITLE
bug(fmt): `line_length` not respected for custom error definition

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4021]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44159a 2023-01-03T00:04:41.810446Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge fmt` does not respect the `line_length` rule for this custom error definition:

```solidity
    error SablierV2Pro__NetDepositAmountNotEqualToSegmentAmountsSum(uint128 netDepositAmount, uint128 segmentAmountsSum);
```

The above has 121 lines, which is 1 line greater than the value of 120 I have set for `line_length`. If I refactor the code like this:

```solidity
    error SablierV2Pro__NetDepositAmountNotEqualToSegmentAmountsSum(
        uint128 netDepositAmount,
        uint128 segmentAmountsSum
    );
```

Running `forge fmt` will format the code to be like in the first code snippet, thus making Solhint throw an error.

**Update**: I did some more testing and it looks like the `line_length` rule is not respected for any of the custom error definitions in my code base.

### Additional context

This is my `[fmt]` configuration:

```toml
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
variable_override_spacing = false
wrap_comments = true
```
