### ISSUE TITLE
feat(fmt): `multiline_func_header` equivalent for events

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4024]
### Component

Forge

### Describe the feature you would like

In https://github.com/foundry-rs/foundry/pull/3252, `func_attrs_with_params_multiline` was replaced with `multiline_func_header`, which is great. I like `multiline_func_header` a lot.

There is nothing equivalent for events. I would like my event to be formatted like this:

```solidity
event SetComptroller(
    address indexed owner,
    ISablierV2Comptroller oldComptroller,
    ISablierV2Comptroller newComptroller
);
```

But `forge fmt` re-formats it like this:

```solidity
event SetComptroller(
    address indexed owner, ISablierV2Comptroller oldComptroller, ISablierV2Comptroller newComptroller
);
```

Whereas I would prefer to stick to the same multiline format everywhere (I have set `multiline_func_header` to `all` in my Foundry config).

### Additional context

This is my `[fmt]` configuration:

```toml
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
variable_override_spacing = false
wrap_comments = true
```
