### ISSUE TITLE
Model checker TOML example in README does not compile

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4088]
### Component

Other (please describe)

### Describe the bug

Below is the [current](https://github.com/foundry-rs/foundry/tree/3d5f03836dc5820ba95dadd736d0b17a3c7b4583/config#additional-model-checker-settings) example given in the README for how to set the `model_checker`:

```toml
[profile.default.model_checker]
contracts = { 'src/Contract.sol' = [ 'Contract' ] }
engine = 'chc'
timeout = 10000
targets = [ 'assert' ]
```

This does not compile, unfortunately. The TOML parser throws this error:

> Expected "}", [ \t] or [A-Za-z0-9_\-] but "'" found.

On the second line where the `contracts` object is defined.

Note - I am seeing this error in VSCode.
