### ISSUE TITLE
feat(forge): command-line flag "--fuzz-runs"

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4156]
### Component

Forge

### Describe the feature you would like

Imagine you have multiple test categories, as it is the case in [maple-core-v2](https://github.com/maple-labs/maple-core-v2/tree/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests):

```tree
└── test
   ├── e2e
   ├── fuzz
   └── unit
```

The fuzzing requirements for the end-to-test tests may be different from those for the fuzz tests, for the simple reason that the former may contain advanced testing execution flows, which take a long time to run.

However, bar for the different fuzzing requirements, all test profiles may want to use the same Foundry configuration. The only way to do this today is to create a different Foundry profile for all tests, and duplicate all the non-fuzzing configs:

```toml
[profile.test-e2e]
  fuzz = { runs = 1_000 }
  src = "test"
  verbosity = 4

[profile.test-fuzz]
  fuzz = { runs = 5000 }
  src = "test"
  verbosity = 4

[profile.test-unit]
  fuzz = { runs = 50 }
  src = "test"
  verbosity = 4
```

This is quite verbose and makes the maintenance of config options more difficult because the developer(s) need to remember that the non-fuzzing config options must be kept in-sync.

It would be much easier to have a command-line flag `--fuzz-runs` that always takes precedence over the `fuzz.runs` config option defined in the Foundry config file. This way, the user would be able to write their own custom scripts (in a `package.json` or `Makefile`) that use the desired number of fuzz runs for a specific test profile:

```json
"scripts": {
  "test:e2e": "forge test --fuzz-runs 1000 --match-path 'test/e2e'",
  "test:fuzz": "forge test --fuzz-runs 5000 --match-path 'test/fuzz'",
  "test:unit": "forge test --fuzz-runs 50 --match-path 'test/unit'"
```
