### ISSUE TITLE
bug(forge): invariant runs not sourced from `[fuzz]` section

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4257]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd7850b 2023-02-02T00:05:14.844624Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Start with any Foundry project with invariant tests, e.g. https://github.com/lucas-manuel/invariant-examples, and set the following configuration:

```toml
[profile.default]
  fuzz = { runs = 1_000 }

[profile.default.invariant]
  call_override = false
  fail_on_revert = true
  depth = 100

# Speed up compilation and tests during development
[profile.lite]
  fuzz = { runs = 50 }
  optimizer = false
```

Then, run the invariants like this:

```sh
FOUNDRY_PROFILE=lite forge test --mt "invariant_"
```

You will notice that the number of runs for the invariant tests is 256, and not 50, as one would expect by reading the [Foundry Book](https://book.getfoundry.sh/reference/config/testing#invariant):

> If the common entries are not set in the `[invariant]` section, but are set in the `[fuzz]` (same as `[profile.default.fuzz]`) section, then the values from the `[fuzz]` section will be used.

That is, in the config above the `fuzz.runs` is set to 50, but the invariant test don't use it. Instead, the default number of runs of 256 is applied. This can also be seen by running `forge config`.
