### ISSUE TITLE
Improve diagnostic if multiple etherscan env vars are set

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#4571]
### Component

Forge

### Describe the feature you would like

env vars take precedence over config

following scenario:

```toml
[etherscan]
bsc = { key = "${BSC_ETHERSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
```
export ETHERSCAN_API_KEY=12123423

```
forge verify-contract --chain bsc 0xd8509bee9c9bf012282ad33aba0d87241baf5064 src/Counter.sol:Counter
```

we should rethink that section here and consider return `self.etherscan_api_key` if set, instead of returning the result.

https://github.com/foundry-rs/foundry/blob/93a43535d5e66e5b105c0dbde9042a4d258c076a/config/src/lib.rs#L889-L900

### Additional context
See also https://github.com/foundry-rs/foundry/issues/3861
_No response_
