### ISSUE TITLE
bug(fmt): Very long code not split on multiple lines

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4755]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (04ce078 2023-04-17T00:04:57.209269000Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

I was expecting `forge fmt` to split this code on multiple lines:

```solidity
linear =
new SablierV2LockupLinear({initialAdmin: users.admin.addr, initialComptroller: comptroller, initialNFTDescriptor: descriptor });
dynamic =
new SablierV2LockupDynamic({ initialAdmin: users.admin.addr, initialComptroller: comptroller, initialNFTDescriptor: descriptor,  maxSegmentCount: DefaultParams.MAX_SEGMENT_COUNT });
```

But it doesn't. The code stays put.

Here's my `[fmt]` configuration:

```toml
[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
```
