### ISSUE TITLE
fuzz results differ on local vs github CI 

### ISSUE THREAD

**Issue by xenide** [foundry-rs/foundry#4917]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7bba788 2023-05-10T00:11:46.049317000Z)

### What command(s) is the bug in?

forge snapshot

### Operating System

macOS (Apple Silicon)

### Describe the bug

The fuzz run gas usages differ on my machine vs in github CI. This has been going on for 1-2 months already

Things I tried

- comparing the `forge config` on my machine vs in github CI
  - discovered that the default remappings for `ds-test` was defaulted to `"ds-test/=lib/forge-std/lib/ds-test/src/"` while it was `"ds-test/=lib/solmate/lib/ds-test/src/"` on the github CI
  - tried changing to both, but the fuzz runs gas outputs still differ slightly, and therefore CI tests failing

This is the original `foundry.toml`

```toml
[profile.default]
solc = "0.8.19"
#via_ir = true
bytecode_hash = "none"
optimizer_runs = 1_000_000
libs = ['lib']
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
]
match_path = "test/unit/*.sol"
verbosity = 3
fs_permissions = [
    { access = "write", path = "./script/optimized-deployer-meta" },
    { access = "write", path = "./script/unoptimized-deployer-meta" },
]
ignored_error_codes = []

[profile.integration]
match_path = "test/integration/*.sol"

[profile.differential]
fs_permissions = [{ access = "read", path = "./reference/balancer-v2-monorepo" }]
match_path     = "test/differential/*.sol"

[profile.differential.fuzz]
runs = 10_000

[fmt]
bracket_spacing   = true
wrap_comments     = false
number_underscore = "thousands"
int_types         = "long"

[profile.script]
optimizer_runs = 1_000_000

```
