### ISSUE TITLE
bug(forge): inline configuration not working for `invariant.depth` and `invariant.runs`

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#5080]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1caa0fa 2023-05-30T00:11:10.062347000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have followed the [docs](https://book.getfoundry.sh/reference/config/inline-test-config) and tried to use the inline test config like this:

```solidity
/// forge-config: default.invariant.depth = 1
/// forge-config: default.invariant.runs = 1
function invariant_TokenURI() external useCurrentTimestamp {
    // --- snip --- //
}
```

But that didn't work - see the terminal output here:

https://app.warp.dev/block/evKxZHbWmGqtry0eMdzcs0

It looks like Forge used the default profile settings defined in `foundry.toml`:

```toml
[profile.default.invariant]
  call_override = false # Override unsafe external calls to perform reentrancy checks
  depth = 20            # Number of calls executed in one run
  fail_on_revert = true
  runs = 20
```

Note: I have tried tweaking the comments, i.e. using two slashes (`//`) instead of three (`///`), but that didn't work either.
