### ISSUE TITLE
YulDetails is camel but not snake 

### ISSUE THREAD

**Issue by spockP** [foundry-rs/foundry#5175]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cf104a5 2023-06-18T05:38:12.036372000Z)

### Operating System

macOS (Intel)

### Describe the bug

I have a lot utests that does not work without "via-ir".  However, I want to make the compilation a littler faster. I followed https://github.com/ethereum/solidity/issues/12533#issuecomment-1013073350 and try to set "yulDetails" in my `foundry.toml`. 

And I followed the [foundry-book ](https://github.com/foundry-rs/book/blob/787082310aa3cad6f5625520f7f48a6d99f57260/src/reference/config/solidity-compiler.md?plain=1#L264), and add `optimizer_details.yul_details` to my `foundry.toml`: 

```toml
via_ir = true
[profile.default.optimizer_details]
peephole = false
inliner = false
jumpdest_remover = false
order_literals = false
deduplicate = false
cse = false
constant_optimizer = false
yul = true
[profile.default.optimizer_details.yul_details]
stack_allocation = true
optimizer_steps = ""
```

Unluckily, the above configuration does not work. The `yul_details` and its child keys should all be in `Camel Case`. The working configuration is as follows: 

```toml
via_ir = true
[profile.default.optimizer_details]
peephole = false
inliner = false
jumpdestRemover = false
orderLiterals = false
deduplicate = false
cse = false
constantOptimizer = false
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = ""
```

If the `snake case` is expected, I think this must be a bug. Or you should update the `foundry book`.
