### ISSUE TITLE
Bug: Foundry does not respect optimizerSteps setting for Yul

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#5449]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

Foundry.toml configuration 

```toml
[profile.default.optimizer_details]
# constantOptimizer = true
yul = true
# this sets the `yulDetails` of the `optimizer_details` for the `default` profile
[profile.default.optimizer_details.yulDetails]
stackAllocation = false
optimizerSteps = 'u'
```

Build output yields 

```
optimizerSteps: u:fDnTOc
```

**Comment by sambacha** [comment]
What is more if we find the default settings we see:

```toml
# this sets the `yulDetails` of the `optimizer_details` for the `default` profile
[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'dhfoDgvulfnTUtnIf'
```

https://github.com/foundry-rs/foundry/blob/master/config/src/lib.rs#L4198C44-L4198C61
