### ISSUE TITLE
Optimize installation speed when building from source on Windows

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#5483]
### Component

Other (please describe)

### Describe the feature you would like

The current installation time on Windows OS (i.e. building Foundry from source) is crazy long. In order to replicate the normal installation behaviour, you can run the following GH CI action on any test repo:

```yml
name: 🛠 Test Native Windows Foundry Build

on: [workflow_dispatch]

jobs:
  build:
    name: Foundry
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Foundry from source
        run: cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli anvil chisel
```

![image](https://github.com/foundry-rs/foundry/assets/25297591/501b56c5-7ba9-4d9a-9f53-a066d3b357a9)

For `foundry-cli`, `anvil`, and `chisel` together you usually have +90mins build time, which is honestly not acceptable. WSL works of course as an alternative, but I would like to still discuss potential remediations here.

### Additional context

My current local installation time:

![image](https://github.com/foundry-rs/foundry/assets/25297591/de787972-1c15-40b8-86d1-258ecdc6fa2e)
