### ISSUE TITLE
feat: support external sections in `foundry.toml`

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#5866]
### Component

Forge

### Describe the feature you would like

There are various requests and use cases for adding support for custom sections to `foundry.toml`:
- [scopelint](https://github.com/ScopeLift/scopelint) is a tool for linting forge projects. Instead of having it's own config file, it would be nice to just let users define the settings directly in the forge config file
- In https://github.com/foundry-rs/foundry/issues/4808, there's requests to support parsing the config file so it can be extended to contain settings for [forge deploy](https://github.com/wighawag/forge-deploy) or Noir circuits

Currently, you can add a custom section to the config file, but it will trigger a warning:

```
$ forge test
warning: Unknown section [scopelint] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.scopelint] instead or run `forge config --fix`.
```

Therefore, I'd suggest requiring that unknown sections are prefixed with something like `external.`, which makes it clear they are for other tools that extend foundry and we'd suppress the warning for those sections.

For example:

```toml
# Default foundry configuration
[profile.default]
optimizer = false

[profile.ci]
optimizer = true

# Custom sections for other tools
[external.scopelint]
some_flag = 1

[external.forge_deploy]
another_setting = 123
```
