### ISSUE TITLE
Anvil fork is blocking the terminal

### ISSUE THREAD

**Issue by percojazz** [foundry-rs/foundry#6285]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

0.2.0 (57180fc 2023-11-09T01:52:52.702931742Z)

### What command(s) is the bug in?

anvill --fork-url xxxx

### Operating System

Linux

### Describe the bug

After I fork the blockchain using the anvil fork command, I am willing to send some transactions that I have regrouped into init_wallet.sh. But I am unable to do so as the the fork command has renderedmy terminal unresponsive.
My use case is that I am launching foundry fom a docker compose file and I am willing to send a few tx after forking in the following way:
```
image: ghcr.io/foundry-rs/foundry:latest
    restart: unless-stopped
    volumes:
      - ./init_wallet.sh:/init_wallet.sh
    entrypoint: anvil --fork-url "https://mainnet.infura.io/v3/xxx" --host "0.0.0.0" --silent
    command: ["sh", "init_wallet.sh"]
```
Thanks for looking at this
