### ISSUE TITLE
`forge script` fails with Arbitrum One endpoint when Etherscan config is set up

### ISSUE THREAD

**Issue by 0x-r4bbit** [foundry-rs/foundry#6580]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cdbaf9d 2023-12-12T00:24:56.406286000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running this deployment command:

```sh
forge script script/DeployContracts.s.sol \
  --rpc-url $RPC_ALCHEMY_ARBITRUM \
  --broadcast \
  --verify \
  --ledger
```

Results in the following error:

```
At least one of `url` or `chain` must be present for Etherscan config `arbitrum_one`
```

However, taking a look at the `arbitrum_one` configs in `foundry.toml`, they do exist:

```toml
[etherscan]
  arbitrum_one = { key = "${API_KEY_ARBISCAN}" }
[rpc_endpoints]
  arbitrum_one = "https://arb-mainnet.g.alchemy.com/v2/${API_KEY_ARBITRUM}"
```

I understand that thee's no `url` or `chain` field in the etherscan config for `arbitrum_one`, however, those are typically derived from `--rpc-url` (this works fine with `mainnet`, `goerli`, `sepolia`, `optimism` providing the same kind of configs).

This looks like there's an issue with the `arbitrum_one` field specifically,

Obviously, if I comment out the `etherscan.arbitrum_one` config and omit the `--verify` option in the script command, this goes through just fine.

Also, verifying separately using `forge verify --rpc-url [...]` does the trick.
