### ISSUE TITLE
Dependency Version Mismatch for alloy-rpc-types in foundry-common

### ISSUE THREAD

**Issue by supernovahs** [foundry-rs/foundry#6772]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

When adding chisel as a dependency from the foundry-rs GitHub repository, I encountered a version mismatch error for alloy-rpc-types. The required version ^0.1.0 is not available on crates.io, which leads to a failure when building my project.

## Steps to Reproduce
1) Add chisel as a git dependency in my project's Cargo.toml:

[dependencies]
chisel = { git = "https://github.com/foundry-rs/foundry", package = "chisel" }

Run cargo build.
## Expected Behavior
The project should fetch the required alloy-* crates from the specified git repositories and build successfully.

## Current Behavior
Cargo fails to find the required ^0.1.0 version of alloy-rpc-types, as it seems to be unavailable on crates.io. The error message suggests there might be a version that was updated and not re-vendored.

## Error 
```
error: failed to select a version for the requirement `alloy-rpc-types = "^0.1.0"`
candidate versions found which didn't match: 0.0.0-reserved
location searched: crates.io index
required by package `foundry-common v0.2.0 (https://github.com/foundry-rs/foundry#b320027a)`
```

## Possible Solutions
If alloy-rpc-types is an internal dependency or is located in a different repository, could you please advise on how to include it correctly?
If the version ^0.1.0 is supposed to be available on crates.io, could there be a missing publish step?
If this is an issue with vendoring, would it be possible to get instructions on how to vendor the necessary crates for chisel?

**Comment by supernovahs** [comment]
fyi, this same error is for all alloy crates, not just for alloy-rpc-types 
And also for evm inspectors

**Comment by kallydev** [comment]
As alloy has not yet released version 0.1.0 on crates.io, foundry directly specifies the `git` url as the source in the `patch` section of `Cargo.toml`.

https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section

https://github.com/foundry-rs/foundry/blob/d2372db7b38aea9d2f8b055185035a9720338875/Cargo.toml#L203-L231

Or just define it in the `dependencies` section.

```toml
[dependencies]
alloy-providers = { version = "0.1.0", git = "https://github.com/alloy-rs/alloy" }
alloy-pubsub = { version = "0.1.0", git = "https://github.com/alloy-rs/alloy" }
alloy-network = { version = "0.1.0", git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-client = { version = "0.1.0", git = "https://github.com/alloy-rs/alloy" }
alloy-transport-http = { version = "0.1.0", git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-types = { version = "0.1.0", git = "https://github.com/alloy-rs/alloy" }
...
```

**Comment by supernovahs** [comment]
```
[dependencies]
clap = { version = "4", features = ["derive", "env", "unicode", "wrap_help"] }
rustyline = "12"
chisel = {git = "https://github.com/foundry-rs/foundry", package = "chisel"}
alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy" }
alloy-providers = { git = "https://github.com/alloy-rs/alloy" }
alloy-pubsub = { git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-trace-types = { git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport-ipc = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport-ws = { git = "https://github.com/alloy-rs/alloy" }
revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors" }

```
Doing this 
But getting error 

```
error: failed to select a version for the requirement `alloy-rpc-types = "^0.1.0"`
candidate versions found which didn't match: 0.0.0-reserved
location searched: crates.io index
required by package `chisel v0.2.0 (https://github.com/foundry-rs/foundry#b320027a)`
    ... which satisfies git dependency `chisel` (locked to 0.2.0) of package `dwarf v0.1.0 (/Users/supernovahs/Desktop/dwarf)`
if you are looking for the prerelease package it needs to be specified explicitly
    alloy-rpc-types = { version = "0.0.0-reserved" }
perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by kallydev** [comment]
> ```
> [dependencies]
> clap = { version = "4", features = ["derive", "env", "unicode", "wrap_help"] }
> rustyline = "12"
> chisel = {git = "https://github.com/foundry-rs/foundry", package = "chisel"}
> alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy" }
> alloy-providers = { git = "https://github.com/alloy-rs/alloy" }
> alloy-pubsub = { git = "https://github.com/alloy-rs/alloy" }
> alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy" }
> alloy-rpc-trace-types = { git = "https://github.com/alloy-rs/alloy" }
> alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy" }
> alloy-signer = { git = "https://github.com/alloy-rs/alloy" }
> alloy-transport = { git = "https://github.com/alloy-rs/alloy" }
> alloy-transport-http = { git = "https://github.com/alloy-rs/alloy" }
> alloy-transport-ipc = { git = "https://github.com/alloy-rs/alloy" }
> alloy-transport-ws = { git = "https://github.com/alloy-rs/alloy" }
> revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors" }
> ```
> 
> Doing this But getting error
> 
> ```
> error: failed to select a version for the requirement `alloy-rpc-types = "^0.1.0"`
> candidate versions found which didn't match: 0.0.0-reserved
> location searched: crates.io index
> required by package `chisel v0.2.0 (https://github.com/foundry-rs/foundry#b320027a)`
>     ... which satisfies git dependency `chisel` (locked to 0.2.0) of package `dwarf v0.1.0 (/Users/supernovahs/Desktop/dwarf)`
> if you are looking for the prerelease package it needs to be specified explicitly
>     alloy-rpc-types = { version = "0.0.0-reserved" }
> perhaps a crate was updated and forgotten to be re-vendored?
> ```

You also need to specify version `0.1.0` for alloy.

**Comment by supernovahs** [comment]
```
[package]
name = "dwarf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive", "env", "unicode", "wrap_help"] }
rustyline = "12"
chisel = {git = "https://github.com/foundry-rs/foundry", package = "chisel"}
alloy-json-rpc = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-providers = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-pubsub = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-client = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-trace-types = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-types = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-signer = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-transport = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-transport-http = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-transport-ipc = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
alloy-transport-ws = { version = "0.1.0",git = "https://github.com/alloy-rs/alloy" }
revm-inspectors = { version = "0.1.0",git = "https://github.com/paradigmxyz/evm-inspectors" }
```

Error 
```
error: failed to select a version for the requirement `alloy-rpc-types = "^0.1.0"`
candidate versions found which didn't match: 0.0.0-reserved
location searched: crates.io index
required by package `chisel v0.2.0 (https://github.com/foundry-rs/foundry#b320027a)`
    ... which satisfies git dependency `chisel` (locked to 0.2.0) of package `dwarf v0.1.0 (/Users/supernovahs/Desktop/dwarf)`
if you are looking for the prerelease package it needs to be specified explicitly
    alloy-rpc-types = { version = "0.0.0-reserved" }
perhaps a crate was updated and forgotten to be re-vendored?

```

**Comment by kallydev** [comment]
```toml
[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
chisel = { git = "https://github.com/foundry-rs/foundry", package = "chisel" }

[patch.crates-io]
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy" }
alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy" }
alloy-providers = { git = "https://github.com/alloy-rs/alloy" }
alloy-pubsub = { git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport-ipc = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport-ws = { git = "https://github.com/alloy-rs/alloy" }

revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors" }
```
