### ISSUE TITLE
`deployCode`/`getCode` no longer works with different profiles

### ISSUE THREAD

**Issue by amusingaxl** [foundry-rs/foundry#7607]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (14daacf 2024-04-09T00:16:23.595685880Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

This issue is related to #7569

I have a project that requires multiple solidity versions configured as the following:
```toml
[profile.default]
src = 'src'
out = 'out'
script = 'script'
libs = ['lib']
solc_version = '0.8.16'
optimizer = true

[profile.0_6_x]
# `src` must be different fot it to work.
# We also recommend putting all Solidity test files and scripts inside `src*/`.
src = 'src-0_6_x'
out = 'out'
script = 'script-0_6_x'
# The order matters! When using `forge install` with FOUNDRY_PROFILE=0_6_x,
# it will use the first directory as the installation path.
# If the library is compatible with all versions,
# you can install it with the default profile.
libs = ['lib-0_6_x', 'lib']
solc_version = '0.6.12'
optimizer = false
```

Some of the tests are required to deploy contracts from `0_6_x`, so I leverage the `deployCode` cheatcode to do it. The only gotcha was that I needed to run 2 commands when testing:

```bash
FOUNDRY_PROFILE=0_6_x forge build
# builds and runs tests with the default profile
forge test
```

This used to work until recently, but now I'm facing an error like this one:
```
Encountered 1 failing test in src/VestedRewardsDistribution.t.sol:VestedRewardsDistributionTest
[FAIL. Reason: setup failed: No matching artifact found] setUp() (gas: 0)
```

The specific line of code that causes that issue is:
```solidity
deployCode("DssVest.sol:DssVestMintable", abi.encode(address(result.rewardsToken)))
```

`DssVestMintable` is defined in `lib-0_6_x/dss-vest/DssVest.sol`. To force the compiler to find it, there's a `src-0_6_x/Imports.sol` file that imports it.

I checked and the file `out/DssVest.sol/DssVestMintable.json` still exists in the directory, and it's not wiped out when I run `forge build` with no profile or `forge test`.

I'm not sure why this change in behavior was done in the first place, but I would kindly ask if we could have this capability back, otherwise it would be very painful to deal with cross-version compilation with Foundry.
