### ISSUE TITLE
Forge test CI failed with error using latest night build

### ISSUE THREAD

**Issue by y77cao** [foundry-rs/foundry#7620]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-460319558e455611be1de64be8364c65c6896d15

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Test CI suddenly fails today with error "max priority fee per gas higher than max fee per gas". Here's the setup:
```
    - name: Setup foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
  ```

Tests run fine locally. And I was also able to fix the CI by using `nightly-72bc4f4e616c6e2b79ee3582301fbb1d38660857` released 3 days ago. Maybe something off with the latest build?
