### ISSUE TITLE
writeToml should keep original formatting

### ISSUE THREAD

**Issue by Thegaram** [foundry-rs/foundry#7800]
### Component

Forge

### Current behavior

Toml file:

```toml
key1 = "1"

# this is key2
key2 = "2"
```

Script:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity =0.8.24;

import {Script, console} from "forge-std/Script.sol";

contract TomlTest is Script {
    function run() public {
        vm.writeToml("abcd", "test.toml", ".key2");
    }
}
```

Resulting toml file, after running `forge script scripts/foundry/TomlTest.s.sol:TomlTest`:

```toml
key1 = "1"
key2 = "abcd"
```

### Desired behavior

`writeToml` should maintain the original formatting (line breaks, comments):

```toml
key1 = "1"

# this is key2
key2 = "abcd"
```
