### ISSUE TITLE
Contract call after anvil_reset on a fork hangs indefinitely

### ISSUE THREAD

**Issue by cstoneham** [foundry-rs/foundry#7966]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a4d79ac 2024-05-10T00:18:07.559888000Z)

### What command(s) is the bug in?

cast rpc

### Operating System

macOS (Apple Silicon)

### Describe the bug

After resetting a forked network to a given block, the next call to a contract fails (but after this it will succeed).

Steps to Repro:
1. Run foundry, I'm running it in docker-compose like so:
```
  anvil-eth:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-eth
    ports: [ "8550:8545" ]
    platform: linux/amd64/v8
    entrypoint: [ "anvil", "--host", "0.0.0.0", "--fork-url", $MAINNET_RPC_URL, "--steps-tracing"]
```
2. Call `anvil_reset`:
```
cast rpc --rpc-url http://localhost:8550/ anvil_reset '{"jsonRpcUrl": $MAINNET_RPC_URL,"blockNumber":19916015}'
```

3. Make a call to a contract, in this example we're calling the OneInch OffchainOracle:
```
cast call 0x0AdDd25a91563696D8567Df78D5A01C9a991F9B8 --rpc-url http://localhost:8550/ "getRateWithThreshold(address srcToken,address dstToken,bool useWrappers,uint256 thresholdFilter)(uint256)" 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48 0x6b175474e89094c44da98b954eedeac495271d0f false 50
```

4. Notice that this hangs indefinitely.
5. Notice that if you stop this call and fire the same one again, it works.
