### ISSUE TITLE
Feat: forge config init

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#818]
### Component

Forge

### Describe the feature you would like

# Motivation 
I want to auto-generate re-mappings  
Also Im lazy, so I do in existing repo

```sh
# in an existing repo 
forge config --basic > foundry.toml
```
I get

```toml
[default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'solmate/=lib/solmate/src/',
    'weird-erc20/=lib/solmate/lib/weird-erc20/src/',
]
```

## possible aliases 

```sh
$ forge bootstrap
$ forge laforge
$ forge config init
$ forge r
```
