### ISSUE TITLE
bug(cheatcodes): `vm.createDir` can not accessed for write operations 

### ISSUE THREAD

**Issue by Ratimon** [foundry-rs/foundry#8551]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (bdd1137 2024-07-28T00:21:06.817030000Z)

### What command(s) is the bug in?

forge test && forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

What I encountered is that I can not access to the  folders/directory (`deployments/31337`) even though I have set the permission access in foundry.toml

My attempts to call `vm.createDir(path, true);` cheat code from the following snippet:

<img width="1099" alt="Bug 1" src="https://github.com/user-attachments/assets/1031958f-2714-41f7-8f5f-2f036f96d8ec">

[`It is called from this snippet`](https://github.com/Ratimon/redprint-optimism-contracts-examples/blob/reproduce-bug-2/script/deployer/ForgeArtifacts.sol#L147)

For further reference, this is my foundry config and I have set the write access.

<img width="488" alt="BUG-2" src="https://github.com/user-attachments/assets/290b50d8-1121-49fd-8095-9141fee088ea">

[Foundry config file](https://github.com/Ratimon/redprint-optimism-contracts-examples/blob/reproduce-bug-2/foundry.toml)

All source code can be found here: [code](https://github.com/Ratimon/redprint-optimism-contracts-examples/tree/reproduce-bug-2)

**Reproduce Steps**

1)
```bash
git clone -b reproduce-bug-2 git@github.com:Ratimon/redprint-optimism-contracts-examples.git
```

2) install dependencies
```bash
pnpm i
```

3) run `forge test`  or `deploy_100_safe` 

I note that `forge test` basically call solidity script in `deploy_100_safe`  which has [ForgeArtifacts.sol](https://github.com/Ratimon/redprint-optimism-contracts-examples/blob/reproduce-bug-2/script/deployer/ForgeArtifacts.sol#L147) as dependency

**Comment by zerosnacks** [comment]
Confirming that this is an issue, also not strictly related to the `deployments` directory or the `31337` subdirectory. Including a trailing `/` does not appear to cause issues.

**Comment by grandizzy** [comment]
it seems like `fs_permissions` are not defined for default profile (that is the one used by `forge test`), in `foundry.toml` it should be moved under `[profile.default]` e.g.

```toml
[profile.default]
src = "src"
out = "out"
script = 'script'
test = 'test'
libs = ["node_modules", "lib"]
# solc_version = '0.8.15'
auto_detect_solc = true
fs_permissions = [
    { access = 'read-write', path = './deployments/' },
    { access = 'read-write', path = './deployments/31337/' },
    { access = 'read', path = './deploy-config/' },
    { access = 'read', path = './broadcast/' },
    { access = 'read', path = './forge-artifacts/' },
    { access = 'read', path = './out' },
    { access = 'read', path = './script/deploy/' },
    { access = 'read-write', path = './' },
]
```
