### ISSUE TITLE
bug(`config`): `eth_rpc_url` field doesn't resolve environment variables

### ISSUE THREAD

**Issue by QGarchery** [foundry-rs/foundry#8795]
### Component

Forge

### Describe the feature you would like

I want to add the following to `foundry.toml`:
```
eth_rpc_url = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
```
with the goal that it does the same thing as the flag `--rpc-url https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}`, but I'm getting the following error:
```
Could not instantiate forked environment with fork url: https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}
```

So I'm using the following workaround:
- add the following to `foundry.toml`
```
[profile.default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
```
- use `vm.createSelectFork(vm.rpcUrl("mainnet"));` at the beginning of tests

**Comment by zerosnacks** [comment]
Agree that it technically should work but I would recommend to keep using the workaround you are using now over `eth_rpc_url` as I think this is the correct pattern.

I would be in favor of deprecating `eth_rpc_url` post-`1.0` alongside a few of these other global definitions.

**Comment by QGarchery** [comment]
Thanks for the answer @zerosnacks ! Genuinely curious to know why you think the workaround is the correct pattern here, isn't `eth_rpc_url` more straightforward ?

**Comment by zerosnacks** [comment]
It probably is but you usually only require specific tests to run in forked mode or run tests against different forks. The performance overhead of setting up a fork is quite significant so it should be avoided for tests that do not require forking.

When you use `eth_rpc_url` you will likely need to enforce a naming pattern and then filter against it. To then run your entire test suite efficiently you need some way of combining the different test runs.

From: https://book.getfoundry.sh/forge/fork-testing#fork-testing

>Which approach to use? Forking mode affords running an entire test suite against a specific forked environment, while forking cheatcodes provide more flexibility and expressiveness to work with multiple forks in your tests. Your particular use case and testing strategy will help inform which approach to use.

**Comment by sambacha** [comment]
**ETH_RPC_URL** is from *Dapptools* support. 

You can do this already using the following GitHub Workflow setup:

```yaml
name: Test Foundry with RPC Matrix

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  # On-demand
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network:
          - mainnet
          - goerli
          - sepolia
        include:
          - network: mainnet
            rpc_url: ${{ secrets.MAINNET_RPC_URL }}
          - network: goerli
            rpc_url: ${{ secrets.GOERLI_RPC_URL }}
          - network: sepolia
            rpc_url: ${{ secrets.SEPOLIA_RPC_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Set RPC URL
        run: echo "FOUNDRY_ETH_RPC_URL=${{ matrix.rpc_url }}" >> $GITHUB_ENV

      - name: Run Foundry tests
        run: forge test --fork-url ${{ matrix.rpc_url }}
```

**Comment by grandizzy** [comment]
> So I'm using the following workaround:
>
>    add the following to foundry.toml
>
>[profile.default.rpc_endpoints]
>mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
>
>    use vm.createSelectFork(vm.rpcUrl("mainnet")); at the beginning of tests

@QGarchery with `mainnet` key specified as `rpc_enpoint` in toml find you can directly do `forge test --rpc-url mainnet` and no need for the mentioned workaround.
Please close ticket if this is what you were looking for , thank you!

**Comment by QGarchery** [comment]
Thanks @grandizzy, I didn't know you could do this :+1: 

I also checked that it's possible to use the following setting in `foundry.toml`:
```toml
eth_rpc_url = "mainnet"

[profile.default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
```

So it means that it's possible to set up forge to run on a fork globally, without needing to pass any extra parameters in the CLI, which solves my issue !
