### ISSUE TITLE
vm.rollFork header validation error: `excess_blob_gas`

### ISSUE THREAD

**Issue by GlebRadchenko** [foundry-rs/foundry#9297]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e028b92 2024-11-11T00:26:04.968342000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Got following error while running `forge test`:
```
[FAIL: vm.rollFork:  backend: failed committing transaction; header validation error: `excess_blob_gas` not set; `excess_blob_gas` not set;]
```
```solidity
contract FoundryIssueTest is Test {
    uint256 immutable mainnetFork;

    constructor() {
        mainnetFork = vm.createFork("wss://scroll-mainnet.chainstacklabs.com/ws");
    }

    function setUp() public {
        vm.selectFork(mainnetFork);
    }

    function test() public {
        bytes32 targetTxHash = 0xf94774a1f69bba76892141190293ffe85dd8d9ac90a0a2e2b114b8c65764014c;
        vm.rollFork(targetTxHash);
    }
}
```

Note:
same behavior is observed using `vm.createSelectFork`

**Comment by zerosnacks** [comment]
Hi @GlebRadchenko I'm unable to reproduce your the error with the given test

```
Ran 1 test for test/FoundryIssueTest.sol:FoundryIssueTest
[PASS] test() (gas: 3072)
Traces:
  [3072] FoundryIssueTest::test()
    ├─ [0] VM::rollFork(0xf94774a1f69bba76892141190293ffe85dd8d9ac90a0a2e2b114b8c65764014c)
    │   └─ ← [Return] 
    └─ ← [Stop] 

Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 563.78ms (258.04ms CPU time)
```

Would you mind adding your `foundry.toml` / expand on your environment settings?

**Comment by GlebRadchenko** [comment]
Sure, here is my `foundry.toml`:
```toml
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["test/*"]
evm_version = "cancun"
solc-version = "0.8.25"

fs_permissions = [{ access = "read", path = "./"}] # for test json reading
```

no specific env settings:
`rustc 1.82.0 (f6e511eec 2024-10-15)`
