### ISSUE TITLE
The stable release cause the apk not found error

### ISSUE THREAD

**Issue by ChiHaoLu** [foundry-rs/foundry#9894]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### Operating System

Linux

### Describe the bug

I use the below code to build docker in my github actions:
```yaml
  geth_setup:
    image: ghcr.io/foundry-rs/foundry:stable
    platform: linux/amd64
    command: /geth_setup/entry.sh
    environment:
      - PAT=${PAT}
    volumes:
      - ./geth_setup:/geth_setup
      - ./script:/script
    networks:
      - testnet
```

And the my shell script in the `./geth_setup:/geth_setup` get the error: `/geth_setup/entry.sh: 3: apk: not found`

```shell
#!/bin/sh

apk update && apk --no-cache add bash curl coreutils
```
